### ISSUE TITLE
Support for top down profiles and timelines

### ISSUE THREAD

**Issue by devnill** [ruhleder/cpuprofile#1]
I'm working on a project to analyze bottlenecks in a large single page application.  The bottom up profile does most of what I need but it would be very helpful to have the other functionality that DevTools provides. 

I'd be happy to put in a PR or two to add these features if you don't have time to add them in yourself- Are you open to contributions?

**Comment by ruhleder** [comment]
Absolutely. Currently, I don't have time to implement more features myself but I'm more than happy about contributions 👍
